spring:
  application:
    name: joing
  config:
    import: 'optional:aws-parameterstore:/joing/be'

app:
  frontend:
    url: ${frontend.url}

logging:
  level:
    org:
      springframework:
        security: DEBUG
