spring:
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${jdbc.url}  # ${rds.url}
    username: ${jdbc.username}  # ${rds.username}
    password: ${jdbc.password}  # ${rds.password}

  data:
    redis:
      host: ${redis.host}
      port: ${redis.port}